# Generated by Django 5.0.2 on 2025-12-02 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=10)),
                ('nombre_materia', models.CharField(max_length=255)),
                ('seccion', models.CharField(blank=True, max_length=10, null=True)),
                ('dias_json', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('salon', models.CharField(blank=True, max_length=255, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('creditos', models.CharField(blank=True, max_length=10, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('profesor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_escolar_api.maestros')),
            ],
        ),
    ]
